name: setup_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_locales: ^3.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  google_mobile_ads: ^1.2.0
  google_sign_in: ^6.2.1
  path_provider: ^2.0.7
  percent_indicator: ^4.0.1
  provider: ^6.0.4
  shared_preferences: ^2.2.3

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\exercises.json
    - assets/exercises_actualizado.json
    - assets/sounds/victory.mp3
    - assets/photos/
    - assets/locales/
 
