// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxMEk_E38_A5opr-UMrq2xQ0WEphAR1Y',
    appId: '1:604232348381:web:18986753776c8745f62134',
    messagingSenderId: '604232348381',
    projectId: 'dabestudios-set-up',
    authDomain: 'dabestudios-set-up.firebaseapp.com',
    storageBucket: 'dabestudios-set-up.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmvOSbDCytefiycMPtke1-IauMGTCNw98',
    appId: '1:604232348381:android:9288ee6b163b5380f62134',
    messagingSenderId: '604232348381',
    projectId: 'dabestudios-set-up',
    storageBucket: 'dabestudios-set-up.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7bO5rle9UlHvlteK_3G6MsL1xZrLTlk',
    appId: '1:604232348381:ios:2b66c05894500e3df62134',
    messagingSenderId: '604232348381',
    projectId: 'dabestudios-set-up',
    storageBucket: 'dabestudios-set-up.appspot.com',
    iosBundleId: 'com.dabestudios.setupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD7bO5rle9UlHvlteK_3G6MsL1xZrLTlk',
    appId: '1:604232348381:ios:2b66c05894500e3df62134',
    messagingSenderId: '604232348381',
    projectId: 'dabestudios-set-up',
    storageBucket: 'dabestudios-set-up.appspot.com',
    iosBundleId: 'com.dabestudios.setupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRxMEk_E38_A5opr-UMrq2xQ0WEphAR1Y',
    appId: '1:604232348381:web:c57c3b99944d3112f62134',
    messagingSenderId: '604232348381',
    projectId: 'dabestudios-set-up',
    authDomain: 'dabestudios-set-up.firebaseapp.com',
    storageBucket: 'dabestudios-set-up.appspot.com',
  );
}
